import { fromEvent, range } from 'rxjs';
import { map, tap } from 'rxjs/operators';

const texto = document.createElement('div');
texto.innerHTML = `
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam interdum, enim ac eleifend blandit, magna dui consequat velit, vitae sollicitudin velit quam eget arcu. Etiam tincidunt massa eros, a efficitur diam pellentesque nec. Vivamus quis mi eget urna fermentum dignissim. In odio nibh, gravida ut volutpat at, condimentum quis ex. Maecenas sollicitudin luctus enim, ut dictum lectus placerat a. Etiam convallis diam eget urna scelerisque venenatis. Phasellus ac velit felis. Donec odio augue, venenatis ac nisi ut, convallis fringilla augue. Vivamus interdum risus vel blandit finibus. Suspendisse fringilla ornare lectus vel placerat. Mauris mattis rhoncus libero, semper condimentum augue ullamcorper suscipit.
<br><br>
Etiam enim ipsum, tristique eu placerat interdum, tempor ut dui. Cras lacus orci, egestas pharetra lectus nec, iaculis suscipit enim. Proin at convallis tellus, eu tempor purus. Etiam eu nunc non enim feugiat faucibus et id purus. Sed eget maximus sapien. Vivamus eros lacus, faucibus a congue bibendum, eleifend sit amet elit. Sed in bibendum velit, vitae mattis massa. Sed non fermentum erat. Curabitur fermentum tempor eros, et malesuada augue pulvinar a. Praesent vehicula faucibus magna, quis eleifend enim posuere eu. Ut convallis velit mi, vitae porta augue bibendum eu. Nullam libero odio, blandit ac purus laoreet, suscipit tempus erat. Aliquam at orci quis arcu scelerisque interdum. Aliquam erat volutpat.
<br><br>
Donec ac risus vehicula, lacinia eros et, ornare lacus. Morbi vel leo sodales, consequat mauris id, euismod enim. In vitae mauris at leo aliquet lacinia vitae sit amet sapien. Donec ante lectus, aliquam ut pulvinar quis, auctor id massa. Aenean aliquet neque sed nibh venenatis, tincidunt efficitur mauris scelerisque. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Curabitur nulla est, tincidunt quis augue id, vestibulum lobortis tellus.
<br><br>
In hac habitasse platea dictumst. Ut pretium eu est non pellentesque. Nulla lacus ante, ornare quis lorem a, sollicitudin tincidunt erat. Nullam ornare est at volutpat vestibulum. Sed auctor tempor iaculis. Quisque at leo eros. Ut hendrerit arcu eu erat convallis facilisis. Sed porta dictum lacus, in fringilla nunc iaculis in. Aliquam sed finibus arcu. Ut quis urna metus. Aliquam elementum vulputate nisl, non gravida magna porta quis. Vestibulum nec aliquet lorem. Phasellus at nibh et tellus ornare finibus. Pellentesque placerat gravida massa, ut fringilla urna ornare sed.
<br><br>
Fusce lectus quam, molestie sed rhoncus id, sodales et purus. Praesent pharetra sapien et imperdiet feugiat. Integer faucibus felis odio, quis efficitur orci mattis sed. Interdum et malesuada fames ac ante ipsum primis in faucibus. Aliquam quis aliquet eros. Etiam vehicula, libero ut imperdiet lacinia, mi purus dignissim erat, non scelerisque augue lacus a urna. Nam sed dictum nunc. Curabitur at magna eget lacus fermentum pellentesque et quis libero. Donec id risus lacinia, consectetur metus at, lobortis nulla. Pellentesque scelerisque odio porta, rhoncus neque eget, semper erat. Morbi vel condimentum nibh. Sed eu velit nec libero vestibulum auctor ut vel sapien.    
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam interdum, enim ac eleifend blandit, magna dui consequat velit, vitae sollicitudin velit quam eget arcu. Etiam tincidunt massa eros, a efficitur diam pellentesque nec. Vivamus quis mi eget urna fermentum dignissim. In odio nibh, gravida ut volutpat at, condimentum quis ex. Maecenas sollicitudin luctus enim, ut dictum lectus placerat a. Etiam convallis diam eget urna scelerisque venenatis. Phasellus ac velit felis. Donec odio augue, venenatis ac nisi ut, convallis fringilla augue. Vivamus interdum risus vel blandit finibus. Suspendisse fringilla ornare lectus vel placerat. Mauris mattis rhoncus libero, semper condimentum augue ullamcorper suscipit.
<br><br>
Etiam enim ipsum, tristique eu placerat interdum, tempor ut dui. Cras lacus orci, egestas pharetra lectus nec, iaculis suscipit enim. Proin at convallis tellus, eu tempor purus. Etiam eu nunc non enim feugiat faucibus et id purus. Sed eget maximus sapien. Vivamus eros lacus, faucibus a congue bibendum, eleifend sit amet elit. Sed in bibendum velit, vitae mattis massa. Sed non fermentum erat. Curabitur fermentum tempor eros, et malesuada augue pulvinar a. Praesent vehicula faucibus magna, quis eleifend enim posuere eu. Ut convallis velit mi, vitae porta augue bibendum eu. Nullam libero odio, blandit ac purus laoreet, suscipit tempus erat. Aliquam at orci quis arcu scelerisque interdum. Aliquam erat volutpat.
<br><br>
Donec ac risus vehicula, lacinia eros et, ornare lacus. Morbi vel leo sodales, consequat mauris id, euismod enim. In vitae mauris at leo aliquet lacinia vitae sit amet sapien. Donec ante lectus, aliquam ut pulvinar quis, auctor id massa. Aenean aliquet neque sed nibh venenatis, tincidunt efficitur mauris scelerisque. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Curabitur nulla est, tincidunt quis augue id, vestibulum lobortis tellus.
<br><br>
In hac habitasse platea dictumst. Ut pretium eu est non pellentesque. Nulla lacus ante, ornare quis lorem a, sollicitudin tincidunt erat. Nullam ornare est at volutpat vestibulum. Sed auctor tempor iaculis. Quisque at leo eros. Ut hendrerit arcu eu erat convallis facilisis. Sed porta dictum lacus, in fringilla nunc iaculis in. Aliquam sed finibus arcu. Ut quis urna metus. Aliquam elementum vulputate nisl, non gravida magna porta quis. Vestibulum nec aliquet lorem. Phasellus at nibh et tellus ornare finibus. Pellentesque placerat gravida massa, ut fringilla urna ornare sed.
<br><br>
Fusce lectus quam, molestie sed rhoncus id, sodales et purus. Praesent pharetra sapien et imperdiet feugiat. Integer faucibus felis odio, quis efficitur orci mattis sed. Interdum et malesuada fames ac ante ipsum primis in faucibus. Aliquam quis aliquet eros. Etiam vehicula, libero ut imperdiet lacinia, mi purus dignissim erat, non scelerisque augue lacus a urna. Nam sed dictum nunc. Curabitur at magna eget lacus fermentum pellentesque et quis libero. Donec id risus lacinia, consectetur metus at, lobortis nulla. Pellentesque scelerisque odio porta, rhoncus neque eget, semper erat. Morbi vel condimentum nibh. Sed eu velit nec libero vestibulum auctor ut vel sapien.    
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam interdum, enim ac eleifend blandit, magna dui consequat velit, vitae sollicitudin velit quam eget arcu. Etiam tincidunt massa eros, a efficitur diam pellentesque nec. Vivamus quis mi eget urna fermentum dignissim. In odio nibh, gravida ut volutpat at, condimentum quis ex. Maecenas sollicitudin luctus enim, ut dictum lectus placerat a. Etiam convallis diam eget urna scelerisque venenatis. Phasellus ac velit felis. Donec odio augue, venenatis ac nisi ut, convallis fringilla augue. Vivamus interdum risus vel blandit finibus. Suspendisse fringilla ornare lectus vel placerat. Mauris mattis rhoncus libero, semper condimentum augue ullamcorper suscipit.
<br><br>
Etiam enim ipsum, tristique eu placerat interdum, tempor ut dui. Cras lacus orci, egestas pharetra lectus nec, iaculis suscipit enim. Proin at convallis tellus, eu tempor purus. Etiam eu nunc non enim feugiat faucibus et id purus. Sed eget maximus sapien. Vivamus eros lacus, faucibus a congue bibendum, eleifend sit amet elit. Sed in bibendum velit, vitae mattis massa. Sed non fermentum erat. Curabitur fermentum tempor eros, et malesuada augue pulvinar a. Praesent vehicula faucibus magna, quis eleifend enim posuere eu. Ut convallis velit mi, vitae porta augue bibendum eu. Nullam libero odio, blandit ac purus laoreet, suscipit tempus erat. Aliquam at orci quis arcu scelerisque interdum. Aliquam erat volutpat.
<br><br>
Donec ac risus vehicula, lacinia eros et, ornare lacus. Morbi vel leo sodales, consequat mauris id, euismod enim. In vitae mauris at leo aliquet lacinia vitae sit amet sapien. Donec ante lectus, aliquam ut pulvinar quis, auctor id massa. Aenean aliquet neque sed nibh venenatis, tincidunt efficitur mauris scelerisque. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Curabitur nulla est, tincidunt quis augue id, vestibulum lobortis tellus.
<br><br>
In hac habitasse platea dictumst. Ut pretium eu est non pellentesque. Nulla lacus ante, ornare quis lorem a, sollicitudin tincidunt erat. Nullam ornare est at volutpat vestibulum. Sed auctor tempor iaculis. Quisque at leo eros. Ut hendrerit arcu eu erat convallis facilisis. Sed porta dictum lacus, in fringilla nunc iaculis in. Aliquam sed finibus arcu. Ut quis urna metus. Aliquam elementum vulputate nisl, non gravida magna porta quis. Vestibulum nec aliquet lorem. Phasellus at nibh et tellus ornare finibus. Pellentesque placerat gravida massa, ut fringilla urna ornare sed.
<br><br>
Fusce lectus quam, molestie sed rhoncus id, sodales et purus. Praesent pharetra sapien et imperdiet feugiat. Integer faucibus felis odio, quis efficitur orci mattis sed. Interdum et malesuada fames ac ante ipsum primis in faucibus. Aliquam quis aliquet eros. Etiam vehicula, libero ut imperdiet lacinia, mi purus dignissim erat, non scelerisque augue lacus a urna. Nam sed dictum nunc. Curabitur at magna eget lacus fermentum pellentesque et quis libero. Donec id risus lacinia, consectetur metus at, lobortis nulla. Pellentesque scelerisque odio porta, rhoncus neque eget, semper erat. Morbi vel condimentum nibh. Sed eu velit nec libero vestibulum auctor ut vel sapien.    
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam interdum, enim ac eleifend blandit, magna dui consequat velit, vitae sollicitudin velit quam eget arcu. Etiam tincidunt massa eros, a efficitur diam pellentesque nec. Vivamus quis mi eget urna fermentum dignissim. In odio nibh, gravida ut volutpat at, condimentum quis ex. Maecenas sollicitudin luctus enim, ut dictum lectus placerat a. Etiam convallis diam eget urna scelerisque venenatis. Phasellus ac velit felis. Donec odio augue, venenatis ac nisi ut, convallis fringilla augue. Vivamus interdum risus vel blandit finibus. Suspendisse fringilla ornare lectus vel placerat. Mauris mattis rhoncus libero, semper condimentum augue ullamcorper suscipit.
<br><br>
Etiam enim ipsum, tristique eu placerat interdum, tempor ut dui. Cras lacus orci, egestas pharetra lectus nec, iaculis suscipit enim. Proin at convallis tellus, eu tempor purus. Etiam eu nunc non enim feugiat faucibus et id purus. Sed eget maximus sapien. Vivamus eros lacus, faucibus a congue bibendum, eleifend sit amet elit. Sed in bibendum velit, vitae mattis massa. Sed non fermentum erat. Curabitur fermentum tempor eros, et malesuada augue pulvinar a. Praesent vehicula faucibus magna, quis eleifend enim posuere eu. Ut convallis velit mi, vitae porta augue bibendum eu. Nullam libero odio, blandit ac purus laoreet, suscipit tempus erat. Aliquam at orci quis arcu scelerisque interdum. Aliquam erat volutpat.
<br><br>
Donec ac risus vehicula, lacinia eros et, ornare lacus. Morbi vel leo sodales, consequat mauris id, euismod enim. In vitae mauris at leo aliquet lacinia vitae sit amet sapien. Donec ante lectus, aliquam ut pulvinar quis, auctor id massa. Aenean aliquet neque sed nibh venenatis, tincidunt efficitur mauris scelerisque. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Curabitur nulla est, tincidunt quis augue id, vestibulum lobortis tellus.
<br><br>
In hac habitasse platea dictumst. Ut pretium eu est non pellentesque. Nulla lacus ante, ornare quis lorem a, sollicitudin tincidunt erat. Nullam ornare est at volutpat vestibulum. Sed auctor tempor iaculis. Quisque at leo eros. Ut hendrerit arcu eu erat convallis facilisis. Sed porta dictum lacus, in fringilla nunc iaculis in. Aliquam sed finibus arcu. Ut quis urna metus. Aliquam elementum vulputate nisl, non gravida magna porta quis. Vestibulum nec aliquet lorem. Phasellus at nibh et tellus ornare finibus. Pellentesque placerat gravida massa, ut fringilla urna ornare sed.
<br><br>
Fusce lectus quam, molestie sed rhoncus id, sodales et purus. Praesent pharetra sapien et imperdiet feugiat. Integer faucibus felis odio, quis efficitur orci mattis sed. Interdum et malesuada fames ac ante ipsum primis in faucibus. Aliquam quis aliquet eros. Etiam vehicula, libero ut imperdiet lacinia, mi purus dignissim erat, non scelerisque augue lacus a urna. Nam sed dictum nunc. Curabitur at magna eget lacus fermentum pellentesque et quis libero. Donec id risus lacinia, consectetur metus at, lobortis nulla. Pellentesque scelerisque odio porta, rhoncus neque eget, semper erat. Morbi vel condimentum nibh. Sed eu velit nec libero vestibulum auctor ut vel sapien.    
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam interdum, enim ac eleifend blandit, magna dui consequat velit, vitae sollicitudin velit quam eget arcu. Etiam tincidunt massa eros, a efficitur diam pellentesque nec. Vivamus quis mi eget urna fermentum dignissim. In odio nibh, gravida ut volutpat at, condimentum quis ex. Maecenas sollicitudin luctus enim, ut dictum lectus placerat a. Etiam convallis diam eget urna scelerisque venenatis. Phasellus ac velit felis. Donec odio augue, venenatis ac nisi ut, convallis fringilla augue. Vivamus interdum risus vel blandit finibus. Suspendisse fringilla ornare lectus vel placerat. Mauris mattis rhoncus libero, semper condimentum augue ullamcorper suscipit.
<br><br>
Etiam enim ipsum, tristique eu placerat interdum, tempor ut dui. Cras lacus orci, egestas pharetra lectus nec, iaculis suscipit enim. Proin at convallis tellus, eu tempor purus. Etiam eu nunc non enim feugiat faucibus et id purus. Sed eget maximus sapien. Vivamus eros lacus, faucibus a congue bibendum, eleifend sit amet elit. Sed in bibendum velit, vitae mattis massa. Sed non fermentum erat. Curabitur fermentum tempor eros, et malesuada augue pulvinar a. Praesent vehicula faucibus magna, quis eleifend enim posuere eu. Ut convallis velit mi, vitae porta augue bibendum eu. Nullam libero odio, blandit ac purus laoreet, suscipit tempus erat. Aliquam at orci quis arcu scelerisque interdum. Aliquam erat volutpat.
<br><br>
Donec ac risus vehicula, lacinia eros et, ornare lacus. Morbi vel leo sodales, consequat mauris id, euismod enim. In vitae mauris at leo aliquet lacinia vitae sit amet sapien. Donec ante lectus, aliquam ut pulvinar quis, auctor id massa. Aenean aliquet neque sed nibh venenatis, tincidunt efficitur mauris scelerisque. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Curabitur nulla est, tincidunt quis augue id, vestibulum lobortis tellus.
<br><br>
In hac habitasse platea dictumst. Ut pretium eu est non pellentesque. Nulla lacus ante, ornare quis lorem a, sollicitudin tincidunt erat. Nullam ornare est at volutpat vestibulum. Sed auctor tempor iaculis. Quisque at leo eros. Ut hendrerit arcu eu erat convallis facilisis. Sed porta dictum lacus, in fringilla nunc iaculis in. Aliquam sed finibus arcu. Ut quis urna metus. Aliquam elementum vulputate nisl, non gravida magna porta quis. Vestibulum nec aliquet lorem. Phasellus at nibh et tellus ornare finibus. Pellentesque placerat gravida massa, ut fringilla urna ornare sed.
<br><br>
Fusce lectus quam, molestie sed rhoncus id, sodales et purus. Praesent pharetra sapien et imperdiet feugiat. Integer faucibus felis odio, quis efficitur orci mattis sed. Interdum et malesuada fames ac ante ipsum primis in faucibus. Aliquam quis aliquet eros. Etiam vehicula, libero ut imperdiet lacinia, mi purus dignissim erat, non scelerisque augue lacus a urna. Nam sed dictum nunc. Curabitur at magna eget lacus fermentum pellentesque et quis libero. Donec id risus lacinia, consectetur metus at, lobortis nulla. Pellentesque scelerisque odio porta, rhoncus neque eget, semper erat. Morbi vel condimentum nibh. Sed eu velit nec libero vestibulum auctor ut vel sapien.    
`;

const body = document.querySelector('body');
body.append(texto);

const progressBar = document.createElement('div');
progressBar.setAttribute('class', 'progress-bar');
body.append(progressBar);

// función que haga el calculo
const calcularPorcentajeScroll = (event) => {
    const {
        scrollTop,
        scrollHeight,
        clientHeight
    } = event.target.documentElement;

    return (scrollTop / (scrollHeight - clientHeight)) * 100;
};

// Streams
const scroll$ = fromEvent<MouseEvent>(document, 'scroll');
// scroll$.subscribe(console.log);
const progress$ = scroll$.pipe(
    // map(event => calcularPorcentajeScroll(event))
    map(calcularPorcentajeScroll),
    tap(console.log)
);

progress$.subscribe(porcentaje => {
    progressBar.style.width = `${porcentaje}%`;
});